- id: holywell
  name: holywell
  description: Format SQL files with holywell
  entry: npx holywell --write
  language: node
  types: [sql]
  pass_filenames: true

- id: holywell-check
  name: holywell (check only)
  description: Check SQL formatting without modifying files
  entry: npx holywell --check
  language: node
  types: [sql]
  pass_filenames: true
