import { describe, expect, it } from 'bun:test';
import { formatSQL } from '../src/format';
import { parse } from '../src/parser';

function formatWithoutRecoveries(sql: string): string {
  const recoveries: string[] = [];
  const out = formatSQL(sql, {
    onRecover: err => recoveries.push(err.message),
  });
  expect(recoveries).toEqual([]);
  return out;
}

function expectStrictAndRecoveryFree(sql: string): string {
  expect(() => parse(sql, { recover: false })).not.toThrow();
  return formatWithoutRecoveries(sql);
}

describe('dialect and client SQL behavior coverage', () => {
  it('accepts backslashes in Windows paths inside quoted literals', () => {
    const sql = "SET @cmd = 'BACKUP DATABASE foo TO DISK = ''C:\\Backups\\foo.bak'' WITH FORMAT';";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain("C:\\Backups\\foo.bak");
  });

  it('accepts emoji and extended Unicode in quoted literals', () => {
    const sql = "INSERT INTO t(txt) VALUES('snowman ❄ and rocket 🚀');";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain('❄');
    expect(out).toContain('🚀');
  });

  it('preserves COPY FROM stdin blocks terminated by \\\\.', () => {
    const sql = "COPY test_table FROM stdin;\n1\tAlice\t100\n2\tBob\t200\n\\.\nSELECT 1;";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain('COPY test_table FROM stdin;');
    expect(out).toContain('\\.');
    expect(out).toContain('SELECT 1;');
  });

  it('parses AT TIME ZONE postfix expressions in defaults', () => {
    const sql = "CREATE TABLE tz_test(created_at timestamp DEFAULT (now() AT TIME ZONE 'UTC'));";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain("AT TIME ZONE 'UTC'");
  });

  it('allows comments between CREATE VIEW AS and SELECT', () => {
    const sql = "CREATE VIEW v AS\n-- comment here\nSELECT 1;";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain('/* comment here */');
  });

  it('allows comments between the select list and FROM', () => {
    const sql = "SELECT col1\n-- , col2\nFROM t;";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain('-- , col2');
    expect(out.toUpperCase()).toContain('FROM T');
  });

  it('allows comments between UNION ALL and the following SELECT', () => {
    const sql = "SELECT 1 UNION ALL\n-- second part\nSELECT 2;";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain('/* second part */');
    expect(out.toUpperCase()).toContain('UNION ALL');
  });

  it('parses Oracle CONNECT BY hierarchical queries', () => {
    const sql = 'SELECT level FROM dual CONNECT BY level <= 10000;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('CONNECT BY');
  });

  it('parses Oracle CREATE INDEX LOCAL clauses', () => {
    const sql = 'CREATE INDEX idx ON t (col) LOCAL;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('LOCAL');
  });

  it('parses Oracle CREATE INDEX physical and storage clauses', () => {
    const sql = 'CREATE INDEX idx ON t (col) PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING COMPUTE STATISTICS COMPRESS NOSORT STORAGE(INITIAL 64K NEXT 64K) TABLESPACE users PARALLEL 4;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('PCTFREE 10');
    expect(out.toUpperCase()).toContain('TABLESPACE USERS');
    expect(out.toUpperCase()).toContain('PARALLEL 4');
  });

  it('parses GENERATED BY DEFAULT ON NULL AS IDENTITY', () => {
    const sql = 'CREATE TABLE t (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY);';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('GENERATED BY DEFAULT ON NULL AS IDENTITY');
  });

  it('parses CROSS APPLY in UPDATE FROM clauses', () => {
    const sql = "UPDATE o SET total = items.total FROM Orders o CROSS APPLY (SELECT SUM(amount) AS total FROM OrderItems oi WHERE oi.OrderID = o.OrderID) items;";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('CROSS APPLY');
  });

  it('parses schema-qualified names in TRUNCATE', () => {
    const sql = 'TRUNCATE public.class_subjects;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('TRUNCATE PUBLIC.CLASS_SUBJECTS');
  });

  it('parses Snowflake CREATE VIEW COMMENT before AS', () => {
    const sql = "CREATE OR REPLACE VIEW v COMMENT = 'desc' AS SELECT 1;";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain("COMMENT = 'DESC'");
    expect(out.toUpperCase()).toContain(' AS');
  });

  it('accepts $ in Oracle-style system identifiers', () => {
    const sql = 'SELECT * FROM sys.aux_stats$; SELECT * FROM V$FILESTAT;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('SYS.AUX_STATS$');
    expect(out.toUpperCase()).toContain('V$FILESTAT');
  });

  it('parses XML modify() method calls in UPDATE SET', () => {
    const sql = "UPDATE Cars SET Specifications.modify('replace value of (/root/node/text())[1] with \"x\"');";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out.toUpperCase()).toContain('SET SPECIFICATIONS.MODIFY(');
  });

  it('treats GO as a batch separator between statements', () => {
    const sql = 'SELECT 1\nGO\nSELECT 2;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain('\nGO\n');
    expect(out.toUpperCase()).not.toContain('AS GO');
  });

  it('parses psql variable interpolation with schema-qualified object names', () => {
    const sql = 'SELECT * FROM :slschema.gifi; SELECT * FROM country WHERE id = :default_country;';
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain(':slschema.gifi');
    expect(out).toContain(':default_country');
  });

  it('parses inline comments inside INSERT VALUES tuples', () => {
    const sql = "INSERT INTO t (a,b,c) VALUES (\n  'val1',\n  'val2', -- inline comment\n  'val3'\n);";
    const out = expectStrictAndRecoveryFree(sql);
    expect(out).toContain("'val2'");
    expect(out).toContain("'val3'");
  });
});
