// SQL reserved keywords for recognition and uppercasing
export const KEYWORDS = new Set([
  'ABSOLUTE', 'ACTION', 'ADD', 'ALL', 'ALTER', 'AND', 'ANY', 'ARRAY', 'AS', 'ASC',
  'BERNOULLI', 'BETWEEN', 'BIGINT', 'BINARY', 'BIT', 'BLOB', 'BOOLEAN', 'BOTH', 'BY',
  'CASCADE', 'CASE', 'CAST', 'CHAR', 'CHARACTER', 'CHECK', 'CLOB', 'CLOSE',
  'COALESCE', 'COLUMN', 'COMMIT', 'CONCURRENTLY', 'CONFLICT', 'CONSTRAINT', 'CREATE', 'CROSS', 'CUBE', 'CURRENT',
  'CURRENT_DATE', 'CURRENT_ROW', 'CURRENT_TIME', 'CURRENT_TIMESTAMP',
  'CURRENT_USER', 'CURSOR',
  'DATA', 'DATABASE', 'DATE', 'DAY', 'DECIMAL', 'DECLARE', 'DEFAULT', 'DELETE',
  'DESC', 'DISTINCT', 'DO', 'DOUBLE', 'DROP',
  'ELSE', 'END', 'ESCAPE', 'EXCEPT', 'EXCLUDE', 'EXCLUDED', 'EXECUTE', 'EXISTS', 'EXTRACT',
  'FALSE', 'FETCH', 'FILTER', 'FLOAT', 'FOLLOWING', 'FOR', 'FOREIGN', 'FROM', 'FULL',
  'FUNCTION',
  'GRANT', 'GROUP', 'GROUPING',
  'HAVING', 'HOUR',
  'IDENTITY', 'IF', 'ILIKE', 'IN', 'INDEX', 'INNER', 'INSERT', 'INT', 'INTEGER', 'INTERSECT',
  'INTERVAL', 'INTO', 'IS',
  'JOIN', 'JSON', 'JSONB',
  'KEY',
  'LATERAL', 'LEADING', 'LEFT', 'LIKE', 'LIMIT',
  'MATCHED', 'MATERIALIZED', 'MAX', 'MERGE', 'MIN', 'MINUTE', 'MONTH',
  'NATIONAL', 'NATURAL', 'NCHAR', 'NEXT', 'NO', 'NOTHING', 'NOT', 'NOW', 'NULL', 'NULLIF', 'NUMERIC',
  'OF', 'OFFSET', 'ON', 'ONLY', 'OPEN', 'OR', 'ORDER', 'OUTER', 'OVER', 'OVERLAY',
  'PARTITION', 'PLACING', 'PRECEDING', 'PRECISION', 'PRIMARY', 'PROCEDURE', 'POSITION',
  'RANGE', 'REAL', 'RECURSIVE', 'REFERENCES', 'REPEATABLE', 'REPLACE', 'RESTART', 'RETURNING', 'REVOKE', 'RIGHT', 'ROLLBACK', 'ROLLUP',
  'ROW', 'ROW_NUMBER', 'ROWS',
  'SCHEMA', 'SECOND', 'SELECT', 'SERIAL', 'SET', 'SIMILAR', 'SMALLINT', 'SOME', 'SUM',
  'TABLE', 'TABLESAMPLE', 'TEXT', 'THEN', 'TIES', 'TIME', 'TIMESTAMP', 'TO', 'TRAILING', 'TRIGGER', 'TRIM',
  'TRUE', 'TRUNCATE',
  'UNBOUNDED', 'UNION', 'UNIQUE', 'UPDATE', 'UPPER', 'USER', 'USING',
  'VALUES', 'VARCHAR', 'VARYING', 'VIEW',
  'WHEN', 'WHERE', 'WINDOW', 'WITH', 'WITHIN',
  'YEAR',
  // Aggregate/window functions treated as keywords for uppercasing
  'AVG', 'COUNT', 'RANK', 'DENSE_RANK', 'NTILE', 'LAG', 'LEAD',
  'FIRST_VALUE', 'LAST_VALUE', 'NTH_VALUE',
  'ABS', 'CEIL', 'CEILING', 'FLOOR', 'ROUND', 'SIGN',
  'LOWER', 'LENGTH', 'SUBSTRING', 'CONCAT', 'POSITION', 'REPLACE',
  'DATE_TRUNC', 'DATE_PART', 'TO_CHAR', 'EXTRACT', 'AGE',
  'GREATEST', 'LEAST',
  'NEXTVAL', 'CURRVAL', 'SETVAL',
  'CUME_DIST', 'PERCENT_RANK', 'MODE',
  'PERCENTILE_CONT', 'PERCENTILE_DISC',
  'STRING_AGG', 'ARRAY_AGG', 'ARRAY_LENGTH', 'UNNEST', 'GENERATE_SERIES',
  'JSONB_BUILD_OBJECT', 'JSONB_AGG', 'JSONB_EACH', 'JSONB_ARRAY_ELEMENTS', 'JSONB_PATH_QUERY_ARRAY',
]);

// Keywords that are function-like (followed by parens) — should be uppercased
// but not treated as clause keywords
export const FUNCTION_KEYWORDS = new Set([
  'AVG', 'COUNT', 'MAX', 'MIN', 'SUM',
  'ROW_NUMBER', 'RANK', 'DENSE_RANK', 'NTILE', 'LAG', 'LEAD',
  'FIRST_VALUE', 'LAST_VALUE', 'NTH_VALUE',
  'COALESCE', 'NULLIF', 'CAST', 'EXTRACT', 'TRIM',
  'ABS', 'CEIL', 'CEILING', 'FLOOR', 'ROUND', 'SIGN',
  'LOWER', 'UPPER', 'LENGTH', 'SUBSTRING', 'CONCAT', 'POSITION', 'REPLACE',
  'DATE_TRUNC', 'DATE_PART', 'TO_CHAR', 'EXTRACT', 'AGE',
  'GREATEST', 'LEAST',
  'NEXTVAL', 'CURRVAL', 'SETVAL',
  'EXISTS',
  'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'SECOND',
  'CUME_DIST', 'PERCENT_RANK', 'MODE',
  'PERCENTILE_CONT', 'PERCENTILE_DISC',
  'STRING_AGG', 'ARRAY_AGG', 'ARRAY_LENGTH', 'UNNEST', 'GENERATE_SERIES',
  'JSONB_BUILD_OBJECT', 'JSONB_AGG', 'JSONB_EACH', 'JSONB_ARRAY_ELEMENTS', 'JSONB_PATH_QUERY_ARRAY',
  'GROUPING',
]);

export function isKeyword(word: string): boolean {
  return KEYWORDS.has(word.toUpperCase());
}

export function toUpperKeyword(word: string): string {
  if (isKeyword(word)) return word.toUpperCase();
  return word;
}
