// SQL reserved keywords for recognition and uppercasing.
const KEYWORD_LIST = [
  'ABSOLUTE', 'ACTION', 'ADD', 'ALL', 'ALTER', 'AND', 'ANY', 'ARRAY', 'AS', 'ASC',
  'BERNOULLI', 'BETWEEN', 'BIGINT', 'BINARY', 'BIT', 'BLOB', 'BOOLEAN', 'BOTH', 'BY',
  'CASCADE', 'CASE', 'CAST', 'CHAR', 'CHARACTER', 'CHECK', 'CLOB', 'CLOSE',
  'COALESCE', 'COLUMN', 'COMMIT', 'CONCURRENTLY', 'CONFLICT', 'CONSTRAINT', 'CREATE', 'CROSS', 'CUBE', 'CURRENT',
  'CURRENT_DATE', 'CURRENT_ROW', 'CURRENT_TIME', 'CURRENT_TIMESTAMP',
  'CURRENT_USER', 'CURSOR',
  'DATA', 'DATABASE', 'DATE', 'DAY', 'DECIMAL', 'DECLARE', 'DEFAULT', 'DELETE',
  'DESC', 'DISTINCT', 'DO', 'DOUBLE', 'DROP',
  'ELSE', 'END', 'ESCAPE', 'EXCEPT', 'EXCLUDE', 'EXCLUDED', 'EXECUTE', 'EXISTS', 'EXTRACT',
  'FALSE', 'FETCH', 'FILTER', 'FLOAT', 'FOLLOWING', 'FOR', 'FOREIGN', 'FROM', 'FULL',
  'FUNCTION',
  'GRANT', 'GROUP', 'GROUPING',
  'HAVING', 'HOUR',
  'IDENTITY', 'IF', 'ILIKE', 'IN', 'INDEX', 'INNER', 'INSERT', 'INT', 'INTEGER', 'INTERSECT',
  'INTERVAL', 'INTO', 'IS',
  'JOIN', 'JSON', 'JSONB',
  'KEY',
  'LATERAL', 'LEADING', 'LEFT', 'LIKE', 'LIMIT',
  'MATCHED', 'MATERIALIZED', 'MAX', 'MERGE', 'MIN', 'MINUTE', 'MONTH',
  'NATIONAL', 'NATURAL', 'NCHAR', 'NEXT', 'NO', 'NOTHING', 'NOT', 'NOW', 'NULL', 'NULLIF', 'NUMERIC',
  'OF', 'OFFSET', 'ON', 'ONLY', 'OPEN', 'OR', 'ORDER', 'OUTER', 'OVER', 'OVERLAY',
  'PARTITION', 'PLACING', 'POSITION', 'PRECEDING', 'PRECISION', 'PRIMARY', 'PROCEDURE',
  'RANGE', 'REAL', 'RECURSIVE', 'REFERENCES', 'REPEATABLE', 'REPLACE', 'RESTART', 'RETURNING', 'REVOKE', 'RIGHT', 'ROLLBACK', 'ROLLUP',
  'ROW', 'ROW_NUMBER', 'ROWS',
  'SCHEMA', 'SECOND', 'SELECT', 'SERIAL', 'SET', 'SHARE', 'SIMILAR', 'SKIP', 'SMALLINT', 'SOME', 'SUM',
  'TABLE', 'TABLESAMPLE', 'TEXT', 'THEN', 'TIES', 'TIME', 'TIMESTAMP', 'TO', 'TRAILING', 'TRIGGER', 'TRIM',
  'TRUE', 'TRUNCATE',
  'UNBOUNDED', 'UNION', 'UNIQUE', 'UPDATE', 'UPPER', 'USER', 'USING',
  'VALUES', 'VARCHAR', 'VARYING', 'VIEW',
  'WHEN', 'WHERE', 'WINDOW', 'WITH', 'WITHIN', 'WITHOUT',
  'YEAR', 'NOWAIT', 'LOCKED',
  // Aggregate/window functions treated as keywords for uppercasing
  'ABS', 'AGE', 'ARRAY_AGG', 'ARRAY_LENGTH', 'AVG', 'COUNT', 'CUME_DIST', 'CURRVAL',
  'DATE_PART', 'DATE_TRUNC', 'DENSE_RANK', 'FIRST_VALUE', 'FLOOR', 'GENERATE_SERIES',
  'GREATEST', 'JSONB_AGG', 'JSONB_ARRAY_ELEMENTS', 'JSONB_BUILD_OBJECT', 'JSONB_EACH', 'JSONB_PATH_QUERY_ARRAY',
  'LAG', 'LAST_VALUE', 'LEAD', 'LEAST', 'LENGTH', 'LOWER', 'MODE', 'NTH_VALUE', 'NTILE',
  'PERCENT_RANK', 'PERCENTILE_CONT', 'PERCENTILE_DISC', 'RANK', 'ROUND', 'SETVAL',
  'SIGN', 'STRING_AGG', 'SUBSTRING', 'TO_CHAR', 'UNNEST', 'CEIL', 'CEILING', 'CONCAT',
] as const;

const FUNCTION_KEYWORD_LIST = [
  'ABS', 'AGE', 'ALL', 'ANY', 'ARRAY_AGG', 'ARRAY_LENGTH', 'AVG', 'CAST', 'CEIL', 'CEILING',
  'COALESCE', 'CONCAT', 'COUNT', 'CUME_DIST', 'CURRVAL', 'DATE_PART', 'DATE_TRUNC',
  'DENSE_RANK', 'EXISTS', 'EXTRACT', 'FIRST_VALUE', 'FLOOR', 'GENERATE_SERIES',
  'GREATEST', 'GROUPING', 'HOUR', 'JSONB_AGG', 'JSONB_ARRAY_ELEMENTS', 'JSONB_BUILD_OBJECT',
  'JSONB_EACH', 'JSONB_PATH_QUERY_ARRAY', 'LAG', 'LAST_VALUE', 'LEAD', 'LEAST',
  'LENGTH', 'LOWER', 'MAX', 'MIN', 'MINUTE', 'MODE', 'MONTH', 'NEXTVAL', 'NOTHING',
  'NTH_VALUE', 'NTILE', 'NOW', 'NULLIF', 'PERCENT_RANK', 'PERCENTILE_CONT', 'PERCENTILE_DISC',
  'POSITION', 'RANK', 'REPLACE', 'ROW', 'ROW_NUMBER', 'ROUND', 'SECOND', 'SETVAL',
  'SIGN', 'STRING_AGG', 'SUBSTRING', 'SUM', 'TO_CHAR', 'TRIM', 'UNNEST', 'UPPER', 'YEAR', 'DAY',
] as const;

function unique(values: readonly string[]): string[] {
  return [...new Set(values)];
}

export const KEYWORDS = new Set(unique(KEYWORD_LIST));

// Keywords that are function-like (followed by parens) — should be uppercased
// but not treated as clause keywords.
export const FUNCTION_KEYWORDS = new Set(unique(FUNCTION_KEYWORD_LIST));

export function isKeyword(word: string): boolean {
  return KEYWORDS.has(word.toUpperCase());
}
